name: Build/release APP

on:
  push:
    tags:
      - v*.*.*
env:
  GITHUB_TOKEN: ${{ secrets.SS_TOKEN }}
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: echo pat
        run: echo ${{ secrets.SS_TOKEN }}

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Install Dependencies
        run: yarn install

      # - name: build-linux
      #   if: matrix.os == 'ubuntu-latest'
      #   run: yarn run build:linux

      # - name: build-mac
      #   if: matrix.os == 'macos-latest'
      #   run: npm run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: yarn build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            installPackages/*.exe
        # env:
        #   GITHUB_TOKEN: ${{ secrets.SS_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.SS_TOKEN }}
